version: '2'
services:
  db:
    container_name: stripe_donation_form_db
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    container_name: stripe_donation_form_wp
    volumes:
      - "./.www:/var/www/html"
      - "./plugin:/var/www/html/wp-content/plugins/stripe-donation-form"
      - "./docker-scripts:/var/setup-scripts"
    links:
      - db
    build:
        context: ./
        dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
